SELECT 
    u.USER_ID,
    u.NICKNAME,
    CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTRING(U.TLNO, 1, 3), '-', SUBSTRING(U.TLNO, 4, 4), '-', 
           SUBSTRING(U.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
GROUP BY u.USER_ID
HAVING COUNT(BOARD_ID) > 2
ORDER BY u.USER_ID DESC;