SELECT
    a.ANIMAL_ID,
    a.NAME,
    CASE
        WHEN (a.SEX_UPON_INTAKE LIKE '%NEUTERED%' OR a.SEX_UPON_INTAKE LIKE '%SPAYED%') THEN 'O' ELSE 'X'
    END AS '중성화'
FROM ANIMAL_INS a
ORDER BY a.ANIMAL_ID;
