SELECT
    c.CAR_ID,
    CASE
        WHEN h.CAR_ID IS NULL THEN '대여 가능' ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
LEFT JOIN (SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE) h
ON c.CAR_ID = h.CAR_ID
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID DESC;