SELECT f.PRODUCT_ID, f.PRODUCT_NAME, SUM(f.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT f JOIN FOOD_ORDER o
ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY f.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, f.PRODUCT_ID;
