SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_ORDER FO
JOIN
    FOOD_PRODUCT FP
        ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE
    TO_CHAR(FO.PRODUCE_DATE, 'yyyy-mm') = '2022-05'
GROUP BY
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    FP.PRODUCT_ID ASC;