SELECT f.FLAVOR
FROM FIRST_HALF f JOIN (SELECT j.FLAVOR, SUM(j.TOTAL_ORDER) AS TOTAL_ORDER
                       FROM JULY j
                       GROUP BY j.FLAVOR) k
ON f.FLAVOR = k.FLAVOR
ORDER BY (f.TOTAL_ORDER + k.TOTAL_ORDER) DESC
LIMIT 3;