SELECT m.MEMBER_ID, m.MEMBER_NAME, m.GENDER, DATE_FORMAT(m.DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE m
WHERE m.TLNO IS NOT NULL AND MONTH(m.DATE_OF_BIRTH) = 3 AND GENDER = 'W'
ORDER BY m.MEMBER_ID;