SELECT MEMBER_ID, 
MEMBER_NAME, 
GENDER, 
DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_OF_BIRTH 
FROM MEMBER_PROFILE m 
WHERE MONTH(DATE_OF_BIRTH) = 3 AND m.GENDER = 'W' AND m.TLNO IS NOT NULL 
ORDER BY m.MEMBER_ID ASC;