-- 코드를 입력하세요
SELECT
    GOODS.TITLE,
    GOODS.BOARD_ID,
    REPLY.REPLY_ID,
    REPLY.WRITER_ID,
    REPLY.CONTENTS,
    TO_CHAR(REPLY.CREATED_DATE, 'yyyy-mm-dd') AS CREATED_DATE
FROM USED_GOODS_BOARD GOODS
JOIN USED_GOODS_REPLY REPLY
ON GOODS.BOARD_ID = REPLY.BOARD_ID
WHERE
    TO_CHAR(GOODS.CREATED_DATE, 'yyyy-mm') = '2022-10'
ORDER BY REPLY.CREATED_DATE ASC, GOODS.TITLE ASC;