SELECT u.BOARD_ID, u.WRITER_ID, u.TITLE, u.PRICE,
    CASE
        WHEN u.STATUS = 'SALE' THEN '판매중'
        WHEN u.STATUS = 'RESERVED' THEN '예약중'
        WHEN u.STATUS = 'DONE' THEN '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD u
WHERE YEAR(u.CREATED_DATE) = 2022 AND MONTH(u.CREATED_DATE) = 10 AND DAY(u.CREATED_DATE) = 5
ORDER BY u.BOARD_ID DESC;